# Generated by Django 5.1.1 on 2024-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Page_Count',
            new_name='Page_count',
        ),
        migrations.AlterField(
            model_name='book',
            name='Available',
            field=models.BooleanField(),
        ),
    ]
