# Generated by Django 5.1.1 on 2024-09-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='rental_fee',
            new_name='Rental_fee',
        ),
    ]
